version: '3.8'

volumes:
  db:

services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db

  rabbit-queue-listener:
    image: yiisoftware/yii2-php:8.1-apache
    entrypoint: php /app/yii email-queue/listen --verbose
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated

    depends_on:
      - rabbit


  db:
    image: mysql:8.0.31
    restart: always
    environment:
      - MYSQL_DATABASE=buyAndSell
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - '3306:3306'
    volumes:
      - ./docker/data/mysql:/var/lib/mysql

  sphinxsearch:
    image: sphinx:latest
    build:
      context: docker/sphinx
    volumes:
      - ./docker/sphinx/sphinx.conf:/etc/sphinxsearch/sphinx.conf
      - ./docker/sphinx/data:/var/lib/sphinxsearch/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'
    restart: always

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root